apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracker-data
  namespace: tracker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
